// Generated by scripts/generate-tool-provider-pages.mjs from https://api.trytilde.ai/api/v1/mcp/available-tool-groups.
// Do not edit this file directly.

export const providers = [
  {
    "name": "AWS",
    "slug": "aws",
    "initials": "AW",
    "category": "Cloud Infrastructure",
    "summary": "AWS cloud operations, regional availability, documentation, skills, file transfer, and sandboxed multi-step API execution through the official AWS MCP Server. Requests are authenticated with encrypted AWS IAM credentials and SigV4.",
    "auth": [
      "AWS IAM credentials"
    ],
    "iconSources": [],
    "toolCount": 9,
    "tools": []
  },
  {
    "name": "E2B Sandbox",
    "slug": "e2b_sandbox",
    "initials": "E2",
    "category": "Sandbox",
    "summary": "E2B sandbox management, filesystem, patch, and command execution tools.",
    "auth": [
      "E2B API key"
    ],
    "iconSources": [],
    "toolCount": 34,
    "tools": []
  },
  {
    "name": "Firecrawl",
    "slug": "firecrawl",
    "initials": "FI",
    "category": "Search",
    "summary": "Firecrawl web search, scraping, crawling, extraction, monitor, interact, parse, feedback, agent, and research tools.",
    "auth": [
      "Firecrawl API key"
    ],
    "iconSources": [],
    "toolCount": 26,
    "tools": []
  },
  {
    "name": "GitHub",
    "slug": "github",
    "initials": "GI",
    "category": "Developer Tools",
    "summary": "GitHub developer workflow tools for issues, pull requests, code, Actions, checks, releases, reactions, search, users, and organizations.",
    "auth": [
      "Personal access token",
      "OAuth app",
      "GitHub App",
      "Tilde-managed OAuth"
    ],
    "iconSources": [],
    "toolCount": 78,
    "tools": []
  },
  {
    "name": "Google Analytics",
    "slug": "google_analytics",
    "initials": "GO",
    "category": "Analytics",
    "summary": "Google Analytics tools for GA4 Admin, Data API reports, audience exports/lists, report tasks, and Measurement Protocol events.",
    "auth": [
      "Tilde-managed Google OAuth"
    ],
    "iconSources": [],
    "toolCount": 74,
    "tools": []
  },
  {
    "name": "Google Calendar",
    "slug": "google_calendar",
    "initials": "GO",
    "category": "Calendar",
    "summary": "Google Calendar integration for managing events, scheduling, and calendar access.",
    "auth": [
      "Tilde-managed OAuth"
    ],
    "iconSources": [],
    "toolCount": 9,
    "tools": []
  },
  {
    "name": "Google Docs",
    "slug": "google_docs",
    "initials": "GO",
    "category": "Documents",
    "summary": "Google Docs integration for creating, reading, and editing documents.",
    "auth": [
      "Tilde-managed OAuth"
    ],
    "iconSources": [],
    "toolCount": 6,
    "tools": []
  },
  {
    "name": "Google Drive",
    "slug": "google_drive",
    "initials": "GO",
    "category": "File Storage",
    "summary": "Google Drive integration for searching, uploading, downloading, and managing files and folders.",
    "auth": [
      "Tilde-managed OAuth"
    ],
    "iconSources": [],
    "toolCount": 10,
    "tools": []
  },
  {
    "name": "Google Mail",
    "slug": "google_mail",
    "initials": "GO",
    "category": "Email",
    "summary": "Google Mail integration for sending and reading emails via the Gmail API.",
    "auth": [
      "Tilde-managed OAuth"
    ],
    "iconSources": [],
    "toolCount": 11,
    "tools": []
  },
  {
    "name": "Google Search Console",
    "slug": "google_search_console",
    "initials": "GO",
    "category": "Search",
    "summary": "Google Search Console tools for property management, search analytics, URL inspection, indexing diagnostics, and sitemap management.",
    "auth": [
      "Tilde-managed OAuth"
    ],
    "iconSources": [],
    "toolCount": 19,
    "tools": []
  },
  {
    "name": "Google Sheets",
    "slug": "google_sheets",
    "initials": "GO",
    "category": "Spreadsheets",
    "summary": "Google Sheets integration for reading, writing, and managing spreadsheet data.",
    "auth": [
      "Tilde-managed OAuth"
    ],
    "iconSources": [],
    "toolCount": 10,
    "tools": []
  },
  {
    "name": "Message agent",
    "slug": "chatkit_agent_message",
    "initials": "ME",
    "category": "Chat",
    "summary": "Send a ChatKit message to the agent bound to this provider and stream its response.",
    "auth": [
      "No Auth"
    ],
    "iconSources": [],
    "toolCount": 2,
    "tools": []
  },
  {
    "name": "Message internal agent",
    "slug": "chatkit_internal_agent",
    "initials": "ME",
    "category": "Chat",
    "summary": "Send messages between paired ChatKit agents through an internal ChatKit session.",
    "auth": [],
    "iconSources": [],
    "toolCount": 0,
    "tools": []
  },
  {
    "name": "Modal Sandbox",
    "slug": "modal_sandbox",
    "initials": "MO",
    "category": "Sandbox",
    "summary": "Modal sandbox management, filesystem, patch, and command execution tools.",
    "auth": [
      "Modal token"
    ],
    "iconSources": [],
    "toolCount": 10,
    "tools": []
  },
  {
    "name": "Payload CMS",
    "slug": "payload",
    "initials": "PA",
    "category": "Documents",
    "summary": "Payload CMS document and global content management tools backed by Payload's REST API.",
    "auth": [
      "Payload API key"
    ],
    "iconSources": [],
    "toolCount": 7,
    "tools": []
  },
  {
    "name": "PostHog",
    "slug": "posthog",
    "initials": "PO",
    "category": "Product Analytics",
    "summary": "PostHog product analytics, feature flags, insights, dashboards, cohorts, surveys, experiments, persons, events, annotations, alerts, and project tools backed by direct PostHog REST APIs.",
    "auth": [
      "PostHog API key"
    ],
    "iconSources": [],
    "toolCount": 66,
    "tools": []
  },
  {
    "name": "Sentry",
    "slug": "sentry",
    "initials": "SE",
    "category": "Developer Tools",
    "summary": "Sentry issue discovery, event investigation, assignment, status, and activity-note tools. The deduplicated catalog includes 48 official Sentry MCP definitions and 211 Composio aliases; Nango contributes 0 actions. Inputs and outputs use the upstream JSON schemas.",
    "auth": [
      "Sentry auth token",
      "Sentry OAuth app",
      "Tilde-managed OAuth"
    ],
    "iconSources": [],
    "toolCount": 237,
    "tools": []
  },
  {
    "name": "Slack",
    "slug": "slack",
    "initials": "SL",
    "category": "Chat",
    "summary": "Slack messaging tools backed by a configured Slack bot.",
    "auth": [
      "Tilde-managed OAuth",
      "Slack app"
    ],
    "iconSources": [],
    "toolCount": 53,
    "tools": []
  },
  {
    "name": "Stripe",
    "slug": "stripe",
    "initials": "ST",
    "category": "Payments",
    "summary": "Stripe payment processing integration.",
    "auth": [
      "API Key"
    ],
    "iconSources": [],
    "toolCount": 1,
    "tools": []
  },
  {
    "name": "Tavily",
    "slug": "tavily",
    "initials": "TA",
    "category": "Search",
    "summary": "Tavily web search, extraction, crawl, map, research, and account usage tools.",
    "auth": [
      "Tavily API key"
    ],
    "iconSources": [],
    "toolCount": 6,
    "tools": []
  },
  {
    "name": "Tilde Browser",
    "slug": "tilde_browser",
    "initials": "TI",
    "category": "Browser",
    "summary": "Browserbase-backed Web Browser tools with Tilde managed credential fill.",
    "auth": [],
    "iconSources": [],
    "toolCount": 0,
    "tools": []
  },
  {
    "name": "Tilde Control Plane",
    "slug": "tilde_control_plane",
    "initials": "TI",
    "category": "Tilde",
    "summary": "Authenticated team-scoped Tilde control-plane tools. Team context is inferred from the MCP server/tool instance; org and team administration tools are intentionally hidden.",
    "auth": [
      "No Auth"
    ],
    "iconSources": [],
    "toolCount": 79,
    "tools": []
  },
  {
    "name": "Tilde Human Approval",
    "slug": "tilde_human_approval",
    "initials": "TI",
    "category": "Tilde",
    "summary": "No-auth Tilde human approval tools that can be added to any MCP server so agents can wait for secure user approvals.",
    "auth": [
      "No Auth"
    ],
    "iconSources": [],
    "toolCount": 1,
    "tools": []
  },
  {
    "name": "Tilde Memory Bank",
    "slug": "tilde_memory_bank",
    "initials": "TI",
    "category": "Memory",
    "summary": "Retain, recall, reflect on, and delete documents in one bound Tilde memory bank.",
    "auth": [
      "No Auth"
    ],
    "iconSources": [],
    "toolCount": 4,
    "tools": []
  },
  {
    "name": "Tilde Pay",
    "slug": "tilde_wallet",
    "initials": "TI",
    "category": "Pay",
    "summary": "Tilde Pay tools for balances, deposit information, and agent payments.",
    "auth": [
      "No Auth"
    ],
    "iconSources": [],
    "toolCount": 8,
    "tools": []
  },
  {
    "name": "Tilde Skill Registry",
    "slug": "tilde_skill_registry",
    "initials": "TI",
    "category": "Tilde",
    "summary": "Registry-specific Tilde skill discovery tools. The registry id is bound server-side on each enabled tool instance.",
    "auth": [
      "No Auth"
    ],
    "iconSources": [],
    "toolCount": 4,
    "tools": []
  },
  {
    "name": "Tilde Wiki",
    "slug": "tilde_wiki",
    "initials": "TI",
    "category": "Wiki",
    "summary": "Maintain Markdown pages, semantic relationships, graph queries, revisions, and media assets in one bound Tilde Wiki.",
    "auth": [
      "No Auth"
    ],
    "iconSources": [],
    "toolCount": 43,
    "tools": []
  }
];
